=== asrashley/music-bingo/Extra-Files/schemas/database.json
{
	"$schema": "http://json-schema.org/draft-07/schema#", 
	"$id": "https://raw.githubusercontent.com/asrashley/music-bingo/server/Extra-Files/schemas/database.json", 
    "title": "v4 of database export format",
    "description": "This file format allows an entire Musical Bingo database to be exported and imported.",
	"type": "object",
	"required": [
		"Users",
		"Games",
		"BingoTickets",
		"Tracks",
		"Directories",
		"Songs"
    ],
	"properties": {
		"Users": {
			"$id": "#root/Users", 
			"title": "Users", 
			"type": "array",
			"default": [],
			"items":{
                "$ref": "definitions.json#/definitions/User"
			}
		},
		"Games": {
			"$id": "#root/Games", 
			"title": "Games", 
			"type": "array",
			"default": [],
			"items":{
                "$ref": "definitions.json#/definitions/Game"
			}
		},
		"BingoTickets": {
			"$id": "#root/BingoTickets", 
			"title": "Bingotickets", 
			"type": "array",
			"default": [],
			"items":{
                "$ref": "definitions.json#/definitions/BingoTicket"
			}
		},
		"Tracks": {
			"$id": "#root/Tracks", 
			"title": "Tracks", 
			"type": "array",
			"default": [],
			"items": {
				"oneOf": [
					{
						"$ref": "definitions.json#/definitions/DatabaseTrackV1"
					},
					{
						"$ref": "definitions.json#/definitions/DatabaseTrackV2"
					}
				]
			}
		},
		"Directories": {
			"title": "Directories", 
			"type": "array",
			"default": [],
			"items":{
				"oneOf": [
					{
						"$ref": "definitions.json#/definitions/DirectoryV1"
					},
					{
						"$ref": "definitions.json#/definitions/DirectoryV2"
					}	
				]
			}
		},
		"Songs": {
			"$id": "#root/Songs", 
			"title": "Songs", 
			"type": "array",
			"default": [],
			"items": {
                "$ref": "definitions.json#/definitions/Song"
			}
		}
	}
}

=== asrashley/music-bingo/musicbingo/tests/fixtures/imported-game-v1.json
{
"Users":[],
"Games":[
  {
    "bingo_tickets": [],
    "tracks": [
      1,
      2,
      3,
      4,
      5,
      6,
      7,
      8,
      9,
      10,
      11,
      12,
      13,
      14,
      15,
      16,
      17,
      18,
      19,
      20,
      21,
      22,
      23,
      24,
      25,
      26,
      27,
      28,
      29,
      30,
      31,
      32,
      33,
      34,
      35,
      36,
      37,
      38,
      39,
      40,
      41,
      42,
      43
    ],
    "pk": 1,
    "id": "01-02-03",
    "title": "01-02-03",
    "start": "2020-05-11T08:01:27Z",
    "end": "2020-05-12T08:01:27Z",
    "options": null
  }
],
"BingoTickets":[],
"Tracks":[
  {
    "bingo_tickets": [],
    "game": 1,
    "song": 100,
    "pk": 1,
    "number": 0,
    "start_time": 0
  },
  {
    "bingo_tickets": [],
    "game": 1,
    "song": 101,
    "pk": 2,
    "number": 1,
    "start_time": 30016
  },
  {
    "bingo_tickets": [],
    "game": 1,
    "song": 102,
    "pk": 3,
    "number": 2,
    "start_time": 60016
  },
  {
    "bingo_tickets": [],
    "game": 1,
    "song": 103,
    "pk": 4,
    "number": 3,
    "start_time": 90032
  },
  {
    "bingo_tickets": [],
    "game": 1,
    "song": 104,
    "pk": 5,
    "number": 4,
    "start_time": 120048
  },
  {
    "bingo_tickets": [],
    "game": 1,
    "song": 105,
    "pk": 6,
    "number": 5,
    "start_time": 150064
  },
  {
    "bingo_tickets": [],
    "game": 1,
    "song": 106,
    "pk": 7,
    "number": 6,
    "start_time": 180080
  },
  {
    "bingo_tickets": [],
    "game": 1,
    "song": 107,
    "pk": 8,
    "number": 7,
    "start_time": 210096
  },
  {
    "bingo_tickets": [],
    "game": 1,
    "song": 108,
    "pk": 9,
    "number": 8,
    "start_time": 240112
  },
  {
    "bingo_tickets": [],
    "game": 1,
    "song": 109,
    "pk": 10,
    "number": 9,
    "start_time": 270128
  },
  {
    "bingo_tickets": [],
    "game": 1,
    "song": 110,
    "pk": 11,
    "number": 10,
    "start_time": 300144
  },
  {
    "bingo_tickets": [],
    "game": 1,
    "song": 111,
    "pk": 12,
    "number": 11,
    "start_time": 330160
  },
  {
    "bingo_tickets": [],
    "game": 1,
    "song": 112,
    "pk": 13,
    "number": 12,
    "start_time": 360160
  },
  {
    "bingo_tickets": [],
    "game": 1,
    "song": 113,
    "pk": 14,
    "number": 13,
    "start_time": 390176
  },
  {
    "bingo_tickets": [],
    "game": 1,
    "song": 114,
    "pk": 15,
    "number": 14,
    "start_time": 420192
  },
  {
    "bingo_tickets": [],
    "game": 1,
    "song": 115,
    "pk": 16,
    "number": 15,
    "start_time": 450208
  },
  {
    "bingo_tickets": [],
    "game": 1,
    "song": 116,
    "pk": 17,
    "number": 16,
    "start_time": 480224
  },
  {
    "bingo_tickets": [],
    "game": 1,
    "song": 117,
    "pk": 18,
    "number": 17,
    "start_time": 510240
  },
  {
    "bingo_tickets": [],
    "game": 1,
    "song": 118,
    "pk": 19,
    "number": 18,
    "start_time": 540256
  },
  {
    "bingo_tickets": [],
    "game": 1,
    "song": 119,
    "pk": 20,
    "number": 19,
    "start_time": 560254
  },
  {
    "bingo_tickets": [],
    "game": 1,
    "song": 120,
    "pk": 21,
    "number": 20,
    "start_time": 590270
  },
  {
    "bingo_tickets": [],
    "game": 1,
    "song": 121,
    "pk": 22,
    "number": 21,
    "start_time": 620286
  },
  {
    "bingo_tickets": [],
    "game": 1,
    "song": 122,
    "pk": 23,
    "number": 22,
    "start_time": 650302
  },
  {
    "bingo_tickets": [],
    "game": 1,
    "song": 123,
    "pk": 24,
    "number": 23,
    "start_time": 680318
  },
  {
    "bingo_tickets": [],
    "game": 1,
    "song": 124,
    "pk": 25,
    "number": 24,
    "start_time": 710334
  },
  {
    "bingo_tickets": [],
    "game": 1,
    "song": 125,
    "pk": 26,
    "number": 25,
    "start_time": 740350
  },
  {
    "bingo_tickets": [],
    "game": 1,
    "song": 126,
    "pk": 27,
    "number": 26,
    "start_time": 770366
  },
  {
    "bingo_tickets": [],
    "game": 1,
    "song": 127,
    "pk": 28,
    "number": 27,
    "start_time": 800382
  },
  {
    "bingo_tickets": [],
    "game": 1,
    "song": 128,
    "pk": 29,
    "number": 28,
    "start_time": 830398
  },
  {
    "bingo_tickets": [],
    "game": 1,
    "song": 129,
    "pk": 30,
    "number": 29,
    "start_time": 854118
  },
  {
    "bingo_tickets": [],
    "game": 1,
    "song": 130,
    "pk": 31,
    "number": 30,
    "start_time": 884134
  },
  {
    "bingo_tickets": [],
    "game": 1,
    "song": 131,
    "pk": 32,
    "number": 31,
    "start_time": 914150
  },
  {
    "bingo_tickets": [],
    "game": 1,
    "song": 132,
    "pk": 33,
    "number": 32,
    "start_time": 944166
  },
  {
    "bingo_tickets": [],
    "game": 1,
    "song": 133,
    "pk": 34,
    "number": 33,
    "start_time": 974182
  },
  {
    "bingo_tickets": [],
    "game": 1,
    "song": 134,
    "pk": 35,
    "number": 34,
    "start_time": 1004198
  },
  {
    "bingo_tickets": [],
    "game": 1,
    "song": 135,
    "pk": 36,
    "number": 35,
    "start_time": 1034214
  },
  {
    "bingo_tickets": [],
    "game": 1,
    "song": 136,
    "pk": 37,
    "number": 36,
    "start_time": 1064230
  },
  {
    "bingo_tickets": [],
    "game": 1,
    "song": 137,
    "pk": 38,
    "number": 37,
    "start_time": 1094246
  },
  {
    "bingo_tickets": [],
    "game": 1,
    "song": 138,
    "pk": 39,
    "number": 38,
    "start_time": 1124262
  },
  {
    "bingo_tickets": [],
    "game": 1,
    "song": 139,
    "pk": 40,
    "number": 39,
    "start_time": 1154278
  },
  {
    "bingo_tickets": [],
    "game": 1,
    "song": 140,
    "pk": 41,
    "number": 40,
    "start_time": 1184294
  },
  {
    "bingo_tickets": [],
    "game": 1,
    "song": 141,
    "pk": 42,
    "number": 41,
    "start_time": 1214310
  },
  {
    "bingo_tickets": [],
    "game": 1,
    "song": 142,
    "pk": 43,
    "number": 42,
    "start_time": 1244326
  }
],
"Directories":[
  {
    "parent": null,
    "songs": [
      129,
      120,
      116,
      111,
      101,
      112,
      110,
      117,
      124,
      119,
      134,
      123,
      113,
      139,
      107,
      104,
      122,
      131,
      103,
      140,
      141,
      100,
      126,
      121,
      133,
      109,
      115,
      125,
      135,
      132,
      138,
      130,
      128,
      102,
      127,
      106,
      136,
      114,
      137,
      105,
      108,
      142,
      118
    ],
    "pk": 1,
    "name": "lost+found",
    "title": "lost & found",
    "artist": "Orphaned songs",
    "directories": []
  }
],
"Songs":[
  {
    "directory": 1,
    "tracks": [
      1
    ],
    "pk": 100,
    "filename": "08 Pure & Simple.mp3",
    "title": "Pure & Simple",
    "artist": "Hear'Say",
    "duration": 30016,
    "channels": 2,
    "sample_rate": 44100,
    "sample_width": 16,
    "bitrate": 256,
    "album": "Top Of The Pops 2001 - 2006 [Disc 1]"
  },
  {
    "directory": 1,
    "tracks": [
      2
    ],
    "pk": 101,
    "filename": "01-43- Crazy Chick.mp3",
    "title": "Crazy Chick",
    "artist": "Charlotte Church",
    "duration": 30000,
    "channels": 2,
    "sample_rate": 44100,
    "sample_width": 16,
    "bitrate": 256,
    "album": "100 Hits 2000s Anthems"
  },
  {
    "directory": 1,
    "tracks": [
      3
    ],
    "pk": 102,
    "filename": "17 One Love.mp3",
    "title": "One Love",
    "artist": "Blue",
    "duration": 30016,
    "channels": 2,
    "sample_rate": 44100,
    "sample_width": 16,
    "bitrate": 256,
    "album": "Top Of The Pops 2001 - 2006 [Disc 3]"
  },
  {
    "directory": 1,
    "tracks": [
      4
    ],
    "pk": 103,
    "filename": "07 Maneater.mp3",
    "title": "Maneater",
    "artist": "Nelly Furtado",
    "duration": 30016,
    "channels": 2,
    "sample_rate": 44100,
    "sample_width": 16,
    "bitrate": 256,
    "album": "Top Of The Pops 2001 - 2006 [Disc 1]"
  },
  {
    "directory": 1,
    "tracks": [
      5
    ],
    "pk": 104,
    "filename": "06 Just A Little.mp3",
    "title": "Just A Little",
    "artist": "Liberty X",
    "duration": 30016,
    "channels": 2,
    "sample_rate": 44100,
    "sample_width": 16,
    "bitrate": 256,
    "album": "Top Of The Pops 2001 - 2006 [Disc 1]"
  },
  {
    "directory": 1,
    "tracks": [
      6
    ],
    "pk": 105,
    "filename": "19 You Give Me Something.mp3",
    "title": "You Give Me Something",
    "artist": "James Morrison",
    "duration": 30016,
    "channels": 2,
    "sample_rate": 44100,
    "sample_width": 16,
    "bitrate": 256,
    "album": "Top Of The Pops 2001 - 2006 [Disc 2]"
  },
  {
    "directory": 1,
    "tracks": [
      7
    ],
    "pk": 106,
    "filename": "18 Inner Smile.mp3",
    "title": "Inner Smile",
    "artist": "Texas",
    "duration": 30016,
    "channels": 2,
    "sample_rate": 44100,
    "sample_width": 16,
    "bitrate": 256,
    "album": "Top Of The Pops 2001 - 2006 [Disc 1]"
  },
  {
    "directory": 1,
    "tracks": [
      8
    ],
    "pk": 107,
    "filename": "05 Love Machine.mp3",
    "title": "Love Machine",
    "artist": "Girls Aloud",
    "duration": 30016,
    "channels": 2,
    "sample_rate": 44100,
    "sample_width": 16,
    "bitrate": 256,
    "album": "Top Of The Pops 2001 - 2006 [Disc 1]"
  },
  {
    "directory": 1,
    "tracks": [
      9
    ],
    "pk": 108,
    "filename": "20 All The Things She Said.mp3",
    "title": "All The Things She Said",
    "artist": "t.A.T.u.",
    "duration": 30016,
    "channels": 2,
    "sample_rate": 44100,
    "sample_width": 16,
    "bitrate": 256,
    "album": "Top Of The Pops 2001 - 2006 [Disc 1]"
  },
  {
    "directory": 1,
    "tracks": [
      10
    ],
    "pk": 109,
    "filename": "12 America.mp3",
    "title": "America",
    "artist": "Razorlight",
    "duration": 30016,
    "channels": 2,
    "sample_rate": 44100,
    "sample_width": 16,
    "bitrate": 256,
    "album": "Top Of The Pops 2001 - 2006 [Disc 2]"
  },
  {
