=== asrashley/music-bingo/Extra-Files/schemas/gameTracks_v4.json
{
    "$schema": "http://json-schema.org/draft-07/schema",
    "$id": "https://raw.githubusercontent.com/asrashley/music-bingo/server/Extra-Files/schemas/gameTracks_v4.json",
    "type": "object",
    "title": "Version 4 of the gameTracks Schema",
    "description": "This file format allows a Bingo game to be imported.",
    "default": {},
    "required": [
        "BingoTickets",
        "Directories",
        "Games",
        "Songs",
        "Tracks"
    ],
    "additionalProperties": false,
    "properties": {
        "BingoTickets": {
            "type": "array",
            "title": "List of Bingo tickets in this game",
            "description": "Each ticket has a list of tracks, a unique ID and a unique fingerprint.",
            "uniqueItems": true,
            "default": [],
            "examples": [
                [
                    {
                        "checked": 0,
                        "fingerprint": "417816393719338999789635",
                        "game": 93,
                        "number": 1,
                        "pk": 299,
                        "tracks": [
                            3899,
                            3874,
                            3880,
                            3856,
                            3861,
                            3870,
                            3878,
                            3855,
                            3857,
                            3867,
                            3876,
                            3888,
                            3883,
                            3865,
                            3858
                        ],
                        "user": null
                    },
                    {
                        "checked": 0,
                        "fingerprint": "4764686794174860754929585",
                        "game": 93,
                        "number": 7,
                        "pk": 300,
                        "tracks": [
                            3895,
                            3860,
                            3867,
                            3856,
                            3877,
                            3865,
                            3858,
                            3898,
                            3859,
                            3870,
                            3897,
                            3896,
                            3874,
                            3855,
                            3891
                        ],
                        "user": null
                    }
                ]
            ],
            "additionalItems": false,
            "items": {
                "$ref": "definitions.json#/definitions/BingoTicket"
            }
        },
        "Directories": {
            "type": "array",
            "title": "List of directories",
            "description": "List of directories that contain the songs",
            "uniqueItems": true,
            "default": [],
            "additionalItems": false,
            "items": {
                "$ref": "definitions.json#/definitions/DirectoryV2"
            },
            "examples": [
                {
                    "parent": null,
                    "songs": [
                      31,
                      34,
                      38,
                      27,
                      17,
                      40,
                      18,
                      7,
                      11,
                      19,
                      21,
                      3,
                      2,
                      20,
                      12,
                      22,
                      4,
                      28,
                      6,
                      5,
                      32,
                      1,
                      23,
                      30,
                      37,
                      35,
                      33,
                      16,
                      13,
                      15,
                      9,
                      8,
                      25,
                      24,
                      10,
                      36,
                      29,
                      26,
                      14,
                      39
                    ],
                    "pk": 1,
                    "name": "50s",
                    "title": "The 50s 60 Classic Fifties Hits",
                    "artist": "Various Artists",
                    "directories": []
                  }   
            ]
        },
        "Games": {
            "type": "array",
            "title": "List of Bingo Games",
            "description": "List of bingo game descriptions. Typically only one game in each gameTracks file.",
            "uniqueItems": true,
            "default": [],
            "examples": [
                [
                    {
                        "end": "2020-10-09T19:01:08.138756Z",
                        "id": "20-07-01-3",
                        "options": {
                            "bitrate": 256,
                            "cards_per_page": 0,
                            "checkbox": false,
                            "colour_scheme": "purple",
                            "columns": 5,
                            "crossfade": 500,
                            "doc_per_page": false,
                            "include_artist": true,
                            "number_of_cards": 18,
                            "rows": 3
                        },
                        "pk": 93,
                        "start": "2020-07-01T19:01:08.138756Z",
                        "title": "Rock"
                    }
                ]
            ],
            "additionalItems": false,
            "items": {
                "$ref": "definitions.json#/definitions/Game"
            }
        },
        "Songs": {
            "type": "array",
            "title": "List of songs",
            "description": "List of each song that is used for a track",
            "uniqueItems": true,
            "default": [],
            "additionalItems": false,
            "items": {
                "$ref": "definitions.json#/definitions/Song"
            },
            "examples": [
                [
                    {
                        "album": "The Rock Album [Explicit]",
                        "artist": "The Darkness",
                        "bitrate": 316,
                        "channels": 2,
                        "directory": 121,
                        "duration": 25013,
                        "filename": "03-04- I Believe In A Thing Called Love.mp3",
                        "pk": 3854,
                        "sample_rate": 44100,
                        "sample_width": 16,
                        "title": "I Believe In A Thing Called Love"
                    },
                    {
                        "album": "The Rock Album [Explicit]",
                        "artist": "Whitesnake",
                        "bitrate": 256,
                        "channels": 2,
                        "directory": 121,
                        "duration": 30016,
                        "filename": "01-08- Here I Go Again.mp3",
                        "pk": 3855,
                        "sample_rate": 44100,
                        "sample_width": 16,
                        "title": "Here I Go Again"
                    }
                ]
            ]
        },
        "Tracks": {
            "type": "array",
            "title": "List of tracks",
            "description": "List of each track that is part of the bingo games specified in 'Games'.",
            "uniqueItems": true,
            "default": [],
            "examples": [
                [
                    {
                        "game": 93,
                        "number": 0,
                        "pk": 3854,
                        "song": 3412,
                        "start_time": 9048
                    },
                    {
                        "game": 93,
                        "number": 1,
                        "pk": 3855,
                        "song": 3374,
                        "start_time": 34069
                    }
                ]
            ],
            "additionalItems": false,
            "items": {
                "$ref": "definitions.json#/definitions/GameTrackV4"
            }
        }
    }
}

=== asrashley/music-bingo/client/tests/fixtures/exported-game.json
{
  "BingoTickets": [
    {
      "checked": 0,
      "fingerprint": "3865781315381196319768027795",
      "game": 260,
      "number": 1,
      "pk": 3583,
      "tracks": [
        11007,
        10979,
        10988,
        10962,
        10974,
        11000,
        11008,
        10973,
        10987,
        10994,
        10978,
        10993,
        10965,
        10961,
        11002
      ],
      "user": null
    },
    {
      "checked": 0,
      "fingerprint": "68762802025350280519019818223",
      "game": 260,
      "number": 13,
      "pk": 3584,
      "tracks": [
        10996,
        10998,
        10994,
        10985,
        10965,
        10966,
        10971,
        11008,
        10986,
        10972,
        10987,
        10964,
        11002,
        11000,
        11007
      ],
      "user": null
    },
    {
      "checked": 0,
      "fingerprint": "3301332951717508563571767337",
      "game": 260,
      "number": 25,
      "pk": 3585,
      "tracks": [
        10998,
        10968,
        10981,
        10989,
        11001,
        10964,
        10974,
        10980,
        10963,
        10988,
        10977,
        10979,
        11008,
        10966,
        11007
      ],
      "user": null
    },
    {
      "checked": 0,
      "fingerprint": "728146435170640131068997456389",
      "game": 260,
      "number": 2,
      "pk": 3586,
      "tracks": [
        10973,
        10988,
        10983,
        10972,
        10997,
        11002,
        10989,
        11008,
        10977,
        10999,
        10990,
        11005,
        10985,
        10980,
        10964
      ],
      "user": null
    },
    {
      "checked": 0,
      "fingerprint": "158560815184082031359285426282",
      "game": 260,
      "number": 14,
      "pk": 3587,
      "tracks": [
        11007,
        10992,
        10993,
        10980,
        11000,
        10990,
        10959,
        10978,
        10970,
        11002,
        11008,
        10977,
        11001,
        10979,
        10981
      ],
      "user": null
    },
    {
      "checked": 0,
      "fingerprint": "217098396890435098214389230",
      "game": 260,
      "number": 26,
      "pk": 3588,
      "tracks": [
        10993,
        10961,
        10990,
        10996,
        10971,
        10980,
        10991,
        11008,
        11000,
        10960,
        10998,
        10959,
        10977,
        10973,
        11007
      ],
      "user": null
    },
    {
      "checked": 0,
      "fingerprint": "20364141734689304122294237943",
      "game": 260,
      "number": 3,
      "pk": 3589,
      "tracks": [
        10997,
        10996,
        10986,
        10970,
        11006,
        10982,
        10967,
        10963,
        10999,
        10964,
        10976,
        11005,
        10995,
        10974,
        10994
      ],
      "user": null
    },
    {
      "checked": 0,
      "fingerprint": "8904652791747814282587406",
      "game": 260,
      "number": 15,
      "pk": 3590,
      "tracks": [
        10981,
        10963,
        11007,
        10978,
        10962,
        10964,
        10959,
        10977,
        10967,
        11001,
        10988,
        11002,
        10986,
        10985,
        10973
      ],
      "user": null
    },
    {
      "checked": 0,
      "fingerprint": "23345749472289908703690270938",
      "game": 260,
      "number": 27,
      "pk": 3591,
      "tracks": [
        11003,
        10997,
        11008,
        10978,
        10976,
        10994,
        10999,
        10973,
        10979,
        10989,
        10977,
        10986,
        10959,
        11006,
        10966
      ],
      "user": null
    },
    {
      "checked": 0,
      "fingerprint": "906319114838209773712687646491",
      "game": 260,
      "number": 4,
      "pk": 3592,
      "tracks": [
        11002,
        10988,
        10966,
        10969,
        10983,
        10986,
        11000,
        10978,
        10996,
        11008,
        11003,
        10999,
        10967,
        10984,
        10998
      ],
      "user": null
    },
    {
      "checked": 0,
      "fingerprint": "13129612867297094776726601135",
      "game": 260,
      "number": 16,
      "pk": 3593,
      "tracks": [
        11007,
        10997,
        10961,
        11003,
        10991,
        10984,
        10966,
        10994,
        11005,
        10988,
        10965,
        10968,
        10969,
        10987,
        11006
      ],
      "user": null
    },
    {
      "checked": 0,
      "fingerprint": "67106010435245608625308815",
      "game": 260,
      "number": 28,
      "pk": 3594,
      "tracks": [
        11000,
        10967,
        10974,
        10970,
        10973,
        10975,
        10961,
        10968,
        10989,
        11002,
        10960,
        10982,
        10984,
        11003,
        10995
      ],
      "user": null
    },
    {
      "checked": 0,
      "fingerprint": "748033794403670831564934313163",
      "game": 260,
      "number": 5,
      "pk": 3595,
      "tracks": [
        10994,
        10985,
        11002,
        10968,
        10984,
        11007,
        10999,
        11000,
        10988,
        10991,
        10966,
        10997,
        10969,
        10978,
        10986
      ],
      "user": null
    },
    {
      "checked": 0,
      "fingerprint": "58744162282708554227933360663",
      "game": 260,
      "number": 17,
      "pk": 3596,
      "tracks": [
        10983,
        10968,
        10992,
        10991,
        10963,
        10998,
        11008,
        11001,
        10973,
        11005,
        10971,
        10974,
        10987,
        10978,
        10980
      ],
      "user": null
    },
    {
      "checked": 0,
      "fingerprint": "986575403329950184376351619",
      "game": 260,
      "number": 29,
      "pk": 3597,
      "tracks": [
        10994,
        10978,
        10987,
        10960,
        10995,
        10988,
        10996,
        10992,
        10967,
        10974,
        10975,
        10970,
        11007,
        10976,
        10966
      ],
      "user": null
    },
    {
      "checked": 0,
      "fingerprint": "897463765922787336971260815",
      "game": 260,
      "number": 6,
      "pk": 3598,
      "tracks": [
        10970,
        11000,
        11003,
        10969,
        11001,
        10989,
        11007,
        10972,
        10997,
        10960,
        11006,
        10962,
        10998,
        10991,
        10961
      ],
      "user": null
    },
    {
      "checked": 0,
      "fingerprint": "3389304607899961170977606777",
      "game": 260,
      "number": 18,
      "pk": 3599,
      "tracks": [
        10964,
        10965,
        10987,
        10976,
        10996,
        10985,
        10984,
        11008,
        10975,
        10979,
        10962,
        10999,
        10993,
        10981,
        10982
      ],
      "user": null
    },
    {
      "checked": 0,
      "fingerprint": "252905179652840339879813585",
      "game": 260,
      "number": 30,
      "pk": 3600,
      "tracks": [
        10996,
        10976,
        10961,
        10973,
        11007,
        10964,
        10965,
        10981,
        10975,
        10994,
        10967,
        10987,
        10986,
        10979,
        10993
      ],
      "user": null
    },
    {
      "checked": 0,
      "fingerprint": "144078852616417232669565086183",
      "game": 260,
      "number": 7,
      "pk": 3601,
      "tracks": [
        10964,
        10992,
        11002,
        11008,
        10993,
        10987,
        10999,
        10965,
        10969,
        10994,
        10966,
        10986,
        11006,
        10997,
        10985
      ],
      "user": null
    },
    {
      "checked": 0,
      "fingerprint": "863572878431668647738046018",
      "game": 260,
      "number": 19,
      "pk": 3602,
      "tracks": [
        10981,
        10969,
        11008,
        11002,
        10959,
        10971,
        10979,
        11003,
        10967,
        10991,
        10976,
        11001,
        10985,
        10964,
        10990
      ],
      "user": null
    },
    {
      "checked": 0,
      "fingerprint": "1205148906010819966775095551487",
      "game": 260,
      "number": 31,
      "pk": 3603,
      "tracks": [
        11006,
        11002,
        10974,
        10993,
        10995,
        10980,
        10997,
        11008,
        10967,
        10987,
        10978,
        10998,
        10969,
        11001,
        10971
      ],
      "user": null
    },
    {
      "checked": 0,
      "fingerprint": "1158775816172059052985819305",
      "game": 260,
      "number": 8,
      "pk": 3604,
      "tracks": [
        10981,
        11004,
        11002,
        10962,
        11000,
        10989,
        10974,
        10984,
        10977,
        10969,
        10982,
        10975,
        10987,
        10961,
        10978
      ],
      "user": null
    },
    {
      "checked": 0,
      "fingerprint": "114361228787332985260012110",
      "game": 260,
      "number": 20,
      "pk": 3605,
      "tracks": [
        10960,
        10982,
        10980,
        10989,
        10978,
        10997,
        10977,
        11006,
        10995,
        10961,
        10999,
        11004,
        10959,
        10992,
        10969
      ],
      "user": null
    },
    {
      "checked": 0,
      "fingerprint": "1212244957915161391060219653",
      "game": 260,
      "number": 32,
      "pk": 3606,
      "tracks": [
        10992,
        10978,
        10993,
        11008,
        10962,
        10979,
        10964,
        10967,
        11005,
        10985,
        11004,
        10980,
        10989,
        10960,
        11000
      ],
      "user": null
    },
    {
      "checked": 0,
