=== asrashley/music-bingo/Extra-Files/schemas/gameTracks_v1_v2.json
{
    "$schema": "http://json-schema.org/draft-07/schema",
    "$id": "http://example.com/example.json",
    "type": "array",
    "title": "Version 1 and 2 of the gameTracks Schema",
    "description": "This file format allows the tracks from a Bingo game to be imported.",
    "additionalProperties": false,
    "items": {
        "type": "object",
        "properties": {
            "album": {
                "oneOf": [
                    {
                        "type": "string",
                        "title": "Album name",
                        "description": "Name of album from which track was sampled.",
                        "default": "",
                        "examples": [
                            "The Rock Album [Explicit]"
                        ]
                    },
                    {
                        "type": "array",
                        "title": "Album name (bug)",
                        "description": "Name of album from which track was sampled.",
                        "items": {
                            "type": "string"
                        },
                        "maxItems": 1,
                        "minItems": 1
                    }
                ]
            },
            "artist": {
                "type": "string",
                "title": "Artist name",
                "description": "Name of artist(s) or band credited with this track.",
                "default": "",
                "examples": [
                    "The Darkness"
                ]
            },
            "duration": {
                "type": "integer",
                "title": "Track duration",
                "description": "Duration of track, in milliseconds.",
                "examples": [
                    25013
                ]
            },
            "filename": {
                "type": "string",
                "title": "Filename of song",
                "description": "Filename of source song.",
                "examples": [
                    "03-04- I Believe In A Thing Called Love.mp3"
                ]
            },
            "filepath": {
                "type": "string",
                "title": "Absolute filename of song",
                "description": "Absolute filename of source song.",
                "examples": [
                    "./Clips/Rock/03-04- I Believe In A Thing Called Love.mp3"
                ]
            },
            "count": {
                "type": "integer",
                "title": "Track number",
                "description": "Index of track in a game (1=first track in a game).",
                "examples": [
                    0
                ]
            },
            "refId": {
                "type": "integer",
                "title": "Reference ID",
                "description": "A unique number (across one UI session) for the source song.",
                "examples": [
                    3854
                ]
            },
            "songId": {
                "type": "integer",
                "title": "Song primary key",
                "description": "A unique number (across whole database) for this track.",
                "examples": [
                    3854
                ]
            },
            "song_id": {
                "type": "integer",
                "title": "Song primary key",
                "description": "A unique number (across whole database) for this track.",
                "examples": [
                    3854
                ]
            },
            "start_time": {
                "type": "string",
                "title": "Start time",
                "description": "Time when track starts (mm:ss).",
                "examples": [
                    "0:40",
                    "15:49"
                ]
            },
            "title": {
                "type": "string",
                "title": "Title",
                "description": "Title of this track.",
                "default": "",
                "examples": [
                    "I Believe In A Thing Called Love"
                ]
            }
        },
        "required": [
            "album",
            "artist",
            "duration",
            "title"
        ],
        "dependencies": {
            "songId": ["filename", "count"],
            "song_id": ["filepath", "start_time"]
        },
        "additionalProperties": false
    }

}

=== asrashley/music-bingo/musicbingo/tests/fixtures/gameTracks-v1.json
[
  {
    "album": "Top Of The Pops 2001 - 2006 [Disc 1]",
    "artist": "Hear'Say",
    "count": 1,
    "duration": 30016,
    "filename": "08 Pure & Simple.mp3",
    "songId": 47,
    "title": "Pure & Simple"
  },
  {
    "album": "100 Hits 2000s Anthems",
    "artist": "Charlotte Church",
    "count": 2,
    "duration": 30000,
    "filename": "01-43- Crazy Chick.mp3",
    "songId": 19,
    "title": "Crazy Chick"
  },
  {
    "album": "Top Of The Pops 2001 - 2006 [Disc 3]",
    "artist": "Blue",
    "count": 3,
    "duration": 30016,
    "filename": "17 One Love.mp3",
    "songId": 13,
    "title": "One Love"
  },
  {
    "album": "Top Of The Pops 2001 - 2006 [Disc 1]",
    "artist": "Nelly Furtado",
    "count": 4,
    "duration": 30016,
    "filename": "07 Maneater.mp3",
    "songId": 79,
    "title": "Maneater"
  },
  {
    "album": "Top Of The Pops 2001 - 2006 [Disc 1]",
    "artist": "Liberty X",
    "count": 5,
    "duration": 30016,
    "filename": "06 Just A Little.mp3",
    "songId": 59,
    "title": "Just A Little"
  },
  {
    "album": "Top Of The Pops 2001 - 2006 [Disc 2]",
    "artist": "James Morrison",
    "count": 6,
    "duration": 30016,
    "filename": "19 You Give Me Something.mp3",
    "songId": 53,
    "title": "You Give Me Something"
  },
  {
    "album": "Top Of The Pops 2001 - 2006 [Disc 1]",
    "artist": "Texas",
    "count": 7,
    "duration": 30016,
    "filename": "18 Inner Smile.mp3",
    "songId": 149,
    "title": "Inner Smile"
  },
  {
    "album": "Top Of The Pops 2001 - 2006 [Disc 1]",
    "artist": "Girls Aloud",
    "count": 8,
    "duration": 30016,
    "filename": "05 Love Machine.mp3",
    "songId": 41,
    "title": "Love Machine"
  },
  {
    "album": "Top Of The Pops 2001 - 2006 [Disc 1]",
    "artist": "t.A.T.u.",
    "count": 9,
    "duration": 30016,
    "filename": "20 All The Things She Said.mp3",
    "songId": 191,
    "title": "All The Things She Said"
  },
  {
    "album": "Top Of The Pops 2001 - 2006 [Disc 2]",
    "artist": "Razorlight",
    "count": 10,
    "duration": 30016,
    "filename": "12 America.mp3",
    "songId": 97,
    "title": "America"
  },
  {
    "album": "Top Of The Pops 2001 - 2006 [Disc 2]",
    "artist": "The Darkness",
    "count": 11,
    "duration": 30016,
    "filename": "02 I Believe In A Thing Called Love.mp3",
    "songId": 163,
    "title": "I Believe In A Thing Called Love"
  },
  {
    "album": "100 Hits 2000s Anthems",
    "artist": "Toploader",
    "count": 12,
    "duration": 30000,
    "filename": "01-07- Dancing in the Moonlight.mp3",
    "songId": 181,
    "title": "Dancing in the Moonlight"
  },
  {
    "album": "Top Of The Pops 2001 - 2006 [Disc 1]",
    "artist": "The Pussycat Dolls Feat. Busta Rhymes",
    "count": 13,
    "duration": 30016,
    "filename": "02 Don't Cha.mp3",
    "songId": 179,
    "title": "Don't Cha"
  },
  {
    "album": "Top Of The Pops 2001 - 2006 [Disc 3]",
    "artist": "Ne-Yo",
    "count": 14,
    "duration": 30016,
    "filename": "04 So Sick.mp3",
    "songId": 71,
    "title": "So Sick"
  },
  {
    "album": "Top Of The Pops 2001 - 2006 [Disc 2]",
    "artist": "Take That",
    "count": 15,
    "duration": 30016,
    "filename": "18 Patience.mp3",
    "songId": 139,
    "title": "Patience"
  },
  {
    "album": "Top Of The Pops 2001 - 2006 [Disc 3]",
    "artist": "Sugababes",
    "count": 16,
    "duration": 30016,
    "filename": "12 Round Round.mp3",
    "songId": 137,
    "title": "Round Round"
  },
  {
    "album": "Top Of The Pops 2001 - 2006 [Disc 2]",
    "artist": "Alien Ant Farm",
    "count": 17,
    "duration": 30016,
    "filename": "01 Smooth Criminal.mp3",
    "songId": 3,
    "title": "Smooth Criminal"
  },
  {
    "album": "Top Of The Pops 2001 - 2006 [Disc 3]",
    "artist": "50 Cent",
    "count": 18,
    "duration": 30016,
    "filename": "02 In Da Club.mp3",
    "songId": 2,
    "title": "In Da Club"
  },
  {
    "album": "Greatest Hits",
    "artist": "Bjork",
    "count": 19,
    "duration": 19998,
    "filename": "big_time_sensuality_the_fluke_minimix.mp3",
    "songId": 11,
    "title": "Big Time Sensuality"
  },
  {
    "album": "Top Of The Pops 2001 - 2006 [Disc 1]",
    "artist": "S Club 7",
    "count": 20,
    "duration": 30016,
    "filename": "03 Don't Stop Movin'.mp3",
    "songId": 107,
    "title": "Don't Stop Movin'"
  },
  {
    "album": "Top Of The Pops 2001 - 2006 [Disc 3]",
    "artist": "Outkast",
    "count": 21,
    "duration": 30016,
    "filename": "01 Hey Ya!.mp3",
    "songId": 89,
    "title": "Hey Ya!"
  },
  {
    "album": "Top Of The Pops 2001 - 2006 [Disc 2]",
    "artist": "The Calling",
    "count": 22,
    "duration": 30016,
    "filename": "09 Wherever You Will Go.mp3",
    "songId": 157,
    "title": "Wherever You Will Go"
  },
  {
    "album": "Top Of The Pops 2001 - 2006 [Disc 3]",
    "artist": "The Black Eyed Peas",
    "count": 23,
    "duration": 30016,
    "filename": "06 Shut Up.mp3",
    "songId": 151,
    "title": "Shut Up"
  },
  {
    "album": "Top Of The Pops 2001 - 2006 [Disc 1]",
    "artist": "Sugababes",
    "count": 24,
    "duration": 30016,
    "filename": "04 Push The Button.mp3",
    "songId": 131,
    "title": "Push The Button"
  },
  {
    "album": "Top Of The Pops 2001 - 2006 [Disc 2]",
    "artist": "Fall Out Boy",
    "count": 25,
    "duration": 30016,
    "filename": "03 Dance, Dance.mp3",
    "songId": 31,
    "title": "Dance, Dance"
  },
  {
    "album": "Top Of The Pops 2001 - 2006 [Disc 2]",
    "artist": "Daniel Powter",
    "count": 26,
    "duration": 30016,
    "filename": "13 Bad Day.mp3",
    "songId": 29,
    "title": "Bad Day"
  },
  {
    "album": "Top Of The Pops 2001 - 2006 [Disc 1]",
    "artist": "Scissor Sisters",
    "count": 27,
    "duration": 30016,
    "filename": "09 I Don't Feel Like Dancin'.mp3",
    "songId": 109,
    "title": "I Don't Feel Like Dancin'"
  },
  {
    "album": "Top Of The Pops 2001 - 2006 [Disc 2]",
    "artist": "The Feeling",
    "count": 28,
    "duration": 30016,
    "filename": "17 Sewn.mp3",
    "songId": 167,
    "title": "Sewn"
  },
  {
    "album": "Top Of The Pops 2001 - 2006 [Disc 1]",
    "artist": "Orson",
    "count": 29,
    "duration": 23720,
    "filename": "17 No Tomorrow.mp3",
    "songId": 83,
    "title": "No Tomorrow"
  },
  {
    "album": "Top Of The Pops 2001 - 2006 [Disc 1]",
    "artist": "Gnarls Barkley",
    "count": 30,
    "duration": 30016,
    "filename": "01 Crazy.mp3",
    "songId": 43,
    "title": "Crazy"
  },
  {
    "album": "Top Of The Pops 2001 - 2006 [Disc 3]",
    "artist": "Busted",
    "count": 31,
    "duration": 30016,
    "filename": "15 Sleeping With The Light On.mp3",
    "songId": 17,
    "title": "Sleeping With The Light On"
  },
  {
    "album": "Top Of The Pops 2001 - 2006 [Disc 2]",
    "artist": "Maroon 5",
    "count": 32,
    "duration": 30016,
    "filename": "06 This Love.mp3",
    "songId": 61,
    "title": "This Love"
  },
  {
    "album": "Top Of The Pops 2001 - 2006 [Disc 1]",
    "artist": "Room 5",
    "count": 33,
    "duration": 30016,
    "filename": "14 Make Luv.mp3",
    "songId": 103,
    "title": "Make Luv"
  },
  {
    "album": "Top Of The Pops 2001 - 2006 [Disc 3]",
    "artist": "Shaggy",
    "count": 34,
    "duration": 30016,
    "filename": "10 It Wasn't Me.mp3",
    "songId": 113,
    "title": "It Wasn't Me"
  },
  {
    "album": "Top Of The Pops 2001 - 2006 [Disc 3]",
    "artist": "Nelly Feat. City Spud",
    "count": 35,
    "duration": 30016,
    "filename": "03 Ride Wit Me.mp3",
    "songId": 73,
    "title": "Ride Wit Me"
  },
  {
    "album": "Top Of The Pops 2001 - 2006 [Disc 2]",
    "artist": "Avril Lavigne",
    "count": 36,
    "duration": 30016,
    "filename": "14 Complicated.mp3",
    "songId": 7,
    "title": "Complicated"
  },
  {
    "album": "Top Of The Pops 2001 - 2006 [Disc 3]",
    "artist": "Gabrielle",
    "count": 37,
    "duration": 30016,
    "filename": "18 Out Of Reach.mp3",
    "songId": 37,
    "title": "Out Of Reach"
  },
  {
    "album": "Top Of The Pops 2001 - 2006 [Disc 3]",
    "artist": "Ronan Keating",
    "count": 38,
    "duration": 30016,
    "filename": "19 If Tomorrow Never Comes.mp3",
    "songId": 101,
    "title": "If Tomorrow Never Comes"
  },
  {
    "album": "Top Of The Pops 2001 - 2006 [Disc 2]",
    "artist": "Stereophonics",
    "count": 39,
    "duration": 30016,
    "filename": "15 Maybe Tomorrow.mp3",
    "songId": 127,
    "title": "Maybe Tomorrow"
  },
  {
    "album": "Top Of The Pops 2001 - 2006 [Disc 3]",
    "artist": "Ms. Dynamite",
    "count": 40,
    "duration": 30016,
    "filename": "05 Dy-Na-Mi-Tee.mp3",
    "songId": 67,
    "title": "Dy-Na-Mi-Tee"
  },
  {
    "album": "Top Of The Pops 2001 - 2006 [Disc 2]",
    "artist": "The Kooks",
    "count": 41,
    "duration": 30016,
    "filename": "07 Naive.mp3",
    "songId": 173,
    "title": "Naive"
  },
  {
    "album": "Top Of The Pops 2001 - 2006 [Disc 3]",
    "artist": "Christina Milian",
    "count": 42,
    "duration": 30016,
    "filename": "08 Dip It Low.mp3",
    "songId": 23,
    "title": "Dip It Low"
  },
  {
    "album": "Top Of The Pops 2001 - 2006 [Disc 2]",
    "artist": "Atomic Kitten",
    "count": 43,
    "duration": 30016,
    "filename": "20 Whole Again.mp3",
    "songId": 5,
    "title": "Whole Again"
  }
]
